/*
 * This source file was generated by the Gradle 'init' task
 */
package br.unisul.agenda;


import br.unisul.agenda.model.Usuario;

public class App {
    public static void main(String[] args) {

    }
}